In [5]:
import torch

# 1차원 행렬
t = torch.FloatTensor([0., 1., 2., 3., 4., 5.])
print(t)

print(t.dim())  
print(t.shape)  
print(t.size()) 

print(t[0],t[1],t[-1])
print(t[4:-1],t[3:])

tensor([0., 1., 2., 3., 4., 5.])
1
torch.Size([6])
torch.Size([6])
tensor(0.) tensor(1.) tensor(5.)
tensor([4.]) tensor([3., 4., 5.])


In [14]:
# 2차원 행렬

t=torch.FloatTensor([[1,2,3],
                    [4,5,6,],
                    [7,8,9],
                    [10,11,12]]
                    )
print(t)

print(t.dim())
print(t.size())
print(t.shape)
print()
print(t[:,1])
print(t[:,1].size())
print()
print(t[:,:-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [16]:
#브로드 캐스팅팅
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)
print()
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.]])

tensor([[4., 5.],
        [5., 6.]])


In [26]:
#자주 사용되는 기능들

#matmul,mul
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

print("*matmul 결과* ")
print(m1.matmul(m2))
print("\n*mul 결과*")
print(m1*m2)
print(m1.mul(m2))

#mean(평균)
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0))


#sum(덧셈)
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

#max,argmax
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())
print()
print(t.max(dim=0)) 

*matmul 결과* 
tensor([[ 5.],
        [11.]])

*mul 결과*
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
tensor(2.5000)
tensor([2., 3.])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])
tensor(4.)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
